language: java
cache:
  directories:
    - $HOME/.m2
env:
  global:
    - MAVEN_OPTS="-XX:MaxPermSize=2g -Xmx4g"
    - JAVA_OPTS="-XX:MaxPermSize=2g -Xmx4g"
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
before_install:
  - rvm install 2.2.2
  - rvm use 2.2.2
install:
  - set -e
  - travis_retry sudo apt-get install -y --fix-missing libmagic1 libmagic-dev
  - gem install pdd
script:
  - set -e
  - mvn clean install -Pqulice --errors --batch-mode
  - mvn clean
  - pdd --source=$(pwd) --verbose --file=/dev/null
